version: 2.1

jobs:
  codereview:
    macos:
      xcode: 14.3.1
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler:1.17.2
      - run:
          name: Install SwiftLint
          command: |
            brew update
            brew install swiftlint
      - run:
          name: Install Dependencies
          command: bundle install --path vendor/bundle
      - run:
          name: Run Danger
          command: bundle exec danger
      
workflows:
  code-review-workflow:
    jobs:
      - codereview